modules:
  # --------------------- Views -----------------------
  - input_path: "views/api_view"
    output_path: "views/APIView.md"
  - input_path: "views/list_view"
    output_path: "views/ListView.md"
  - input_path: "views/create_view"
    output_path: "views/CreateView.md"
  - input_path: "views/read_view"
    output_path: "views/ReadView.md"
  - input_path: "views/update_view"
    output_path: "views/UpdateView.md"
  - input_path: "views/delete_view"
    output_path: "views/DeleteView.md"
  - input_path: "views/helpers/path_parameters_type_resolver"
    output_path: "views/helpers/PathParametersTypeResolver.md"

  # -------------------- Viewsets ---------------------
  - input_path: "viewsets/api_viewset"
    output_path: "viewsets/APIViewSet.md"

settings:
  project_root: ninja_crud
  markdown_root: docs/reference
