docs:
  # -------------------- Guides -----------------------
  - title: "Introduction"
    excerpt: "Overview of Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 0
    path: "docs/guides/01-Introduction.md"
  - title: "Installation"
    excerpt: "How to install Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 1
    path: "docs/guides/02-Installation.md"
  - title: "Setup"
    excerpt: "How to setup Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 2
    path: "docs/guides/03-Setup.md"
  - title: "Examples"
    excerpt: "Quick examples of how to use Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 3
    path: "docs/guides/04-Examples.md"

  # ------------------- Reference ---------------------
  # --------------------- Views -----------------------
  - title: "AbstractModelView"
    slug: "abstract-model-view"
    excerpt: "Overview and usage patterns of the AbstractModelView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 0
    path: "docs/reference/views/AbstractModelView.md"
  - title: "ListModelView"
    slug: "list-model-view"
    excerpt: "Guide to implementing and utilizing the ListModelView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 1
    path: "docs/reference/views/ListModelView.md"
  - title: "CreateModelView"
    slug: "create-model-view"
    excerpt: "Instructions on how to leverage the CreateModelView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 2
    path: "docs/reference/views/CreateModelView.md"
  - title: "RetrieveModelView"
    slug: "retrieve-model-view"
    excerpt: "Insight into the workings of the RetrieveModelView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 3
    path: "docs/reference/views/RetrieveModelView.md"
  - title: "UpdateModelView"
    slug: "update-model-view"
    excerpt: "Understanding and applying the UpdateModelView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 4
    path: "docs/reference/views/UpdateModelView.md"
  - title: "DeleteModelView"
    slug: "delete-model-view"
    excerpt: "Exploring the functionality of the DeleteModelView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 5
    path: "docs/reference/views/DeleteModelView.md"
  - title: "Types"
    slug: "types"
    excerpt: "Understanding the different data types used in Django Ninja CRUD views"
    categorySlug: "views"
    hidden: false
    order: 6
    path: "docs/reference/views/helpers/Types.md"

  # -------------------- Viewsets ---------------------
  - title: "ModelViewSet"
    slug: "model-viewset"
    excerpt: "Detailed examination of ModelViewSet and its role in Django Ninja CRUD viewsets"
    categorySlug: "viewsets"
    hidden: false
    order: 0
    path: "docs/reference/viewsets/ModelViewSet.md"
  - title: "BaseModelViewSet"
    slug: "base-model-viewset"
    excerpt: "Insight into the foundation of viewsets with BaseModelViewSet in Django Ninja CRUD"
    categorySlug: "viewsets"
    hidden: false
    order: 1
    path: "docs/reference/viewsets/BaseModelViewSet.md"

  # --------------- Testing Components ----------------
  - title: "PathParameters"
    slug: "path-parameters"
    excerpt: "Navigating the intricacies of path parameters in Django Ninja CRUD testing scenarios"
    categorySlug: "testing-components"
    hidden: false
    order: 0
    path: "docs/reference/testing/core/components/PathParameters.md"
  - title: "QueryParameters"
    slug: "query-parameters"
    excerpt: "Practical tips for handling query parameters for testing in Django Ninja CRUD"
    categorySlug: "testing-components"
    hidden: false
    order: 1
    path: "docs/reference/testing/core/components/QueryParameters.md"
  - title: "Headers"
    slug: "headers"
    excerpt: "Methods to efficiently manage headers in Django Ninja CRUD testing environments"
    categorySlug: "testing-components"
    hidden: false
    order: 2
    path: "docs/reference/testing/core/components/Headers.md"
  - title: "Payloads"
    slug: "payloads"
    excerpt: "Understanding and utilizing payloads in Django Ninja CRUD testing scenarios"
    categorySlug: "testing-components"
    hidden: false
    order: 3
    path: "docs/reference/testing/core/components/Payloads.md"

  # ----------------- Testing Views -------------------
  - title: "AbstractModelViewTest"
    slug: "abstract-model-view-test"
    excerpt: "Provides a declarative and powerful way to test AbstractModelView"
    categorySlug: "testing-views"
    hidden: false
    order: 0
    path: "docs/reference/testing/views/AbstractModelViewTest.md"
  - title: "ListModelViewTest"
    slug: "list-model-view-test"
    excerpt: "Provides a declarative and powerful way to test ListModelView"
    categorySlug: "testing-views"
    hidden: false
    order: 1
    path: "docs/reference/testing/views/ListModelViewTest.md"
  - title: "CreateModelViewTest"
    slug: "create-model-view-test"
    excerpt: "Provides a declarative and powerful way to test CreateModelView"
    categorySlug: "testing-views"
    hidden: false
    order: 2
    path: "docs/reference/testing/views/CreateModelViewTest.md"
  - title: "RetrieveModelViewTest"
    slug: "retrieve-model-view-test"
    excerpt: "Provides a declarative and powerful way to test RetrieveModelView"
    categorySlug: "testing-views"
    hidden: false
    order: 3
    path: "docs/reference/testing/views/RetrieveModelViewTest.md"
  - title: "UpdateModelViewTest"
    slug: "update-model-view-test"
    excerpt: "Provides a declarative and powerful way to test UpdateModelView"
    categorySlug: "testing-views"
    hidden: false
    order: 4
    path: "docs/reference/testing/views/UpdateModelViewTest.md"
  - title: "DeleteModelViewTest"
    slug: "delete-model-view-test"
    excerpt: "Provides a declarative and powerful way to test DeleteModelView"
    categorySlug: "testing-views"
    hidden: false
    order: 5
    path: "docs/reference/testing/views/DeleteModelViewTest.md"

  # ---------------- Testing Viewsets -----------------
  - title: "ModelViewSetTestCase"
    slug: "model-viewset-test-case"
    excerpt: "Expanding test coverage with ModelViewSetTestCase in Django Ninja CRUD"
    categorySlug: "testing-viewsets"
    hidden: false
    order: 0
    path: "docs/reference/testing/viewsets/ModelViewSetTestCase.md"
