docs:
  # -------------------- Guides -----------------------
  - title: "Introduction"
    excerpt: "Overview of Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 0
    path: "docs/guides/01-Introduction.md"
  - title: "Installation"
    excerpt: "How to install Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 1
    path: "docs/guides/02-Installation.md"
  - title: "Setup"
    excerpt: "How to setup Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 2
    path: "docs/guides/03-Setup.md"
  - title: "Examples"
    excerpt: "Quick examples of how to use Django Ninja CRUD"
    categorySlug: "documentation"
    hidden: false
    order: 3
    path: "docs/guides/04-Examples.md"

  # ------------------- Reference ---------------------
  # --------------------- Views -----------------------
  - title: "APIView"
    slug: "api-view"
    excerpt: "Overview and usage patterns of the APIView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 0
    path: "docs/reference/views/APIView.md"
  - title: "ListView"
    slug: "list-view"
    excerpt: "Guide to implementing and utilizing the ListView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 1
    path: "docs/reference/views/ListView.md"
  - title: "CreateView"
    slug: "create-view"
    excerpt: "Instructions on how to leverage the CreateView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 2
    path: "docs/reference/views/CreateView.md"
  - title: "ReadView"
    slug: "read-view"
    excerpt: "Insight into the workings of the ReadView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 3
    path: "docs/reference/views/ReadView.md"
  - title: "UpdateView"
    slug: "update-view"
    excerpt: "Understanding and applying the UpdateView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 4
    path: "docs/reference/views/UpdateView.md"
  - title: "DeleteView"
    slug: "delete-view"
    excerpt: "Exploring the functionality of the DeleteView in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 5
    path: "docs/reference/views/DeleteView.md"
  - title: "PathParametersTypeResolver"
    slug: "path-parameters-type-resolver"
    excerpt: "Detailed examination of the PathParametersTypeResolver in Django Ninja CRUD"
    categorySlug: "views"
    hidden: false
    order: 6
    path: "docs/reference/views/helpers/PathParametersTypeResolver.md"

  # -------------------- Viewsets ---------------------
  - title: "APIViewSet"
    slug: "api-viewset"
    excerpt: "Detailed examination of APIViewSet and its role in Django Ninja CRUD viewsets"
    categorySlug: "viewsets"
    hidden: false
    order: 0
    path: "docs/reference/viewsets/APIViewSet.md"
