import abc
import functools
from typing import TYPE_CHECKING, Any, Callable, Optional, Union

from ninja import NinjaAPI, Router
from ninja.constants import NOT_SET

from ninja_crud.views import utils
from ninja_crud.views.types import Decorator

if TYPE_CHECKING:
    from ninja_crud.viewsets import APIViewSet


class APIView(abc.ABC):
    """
    Base class for creating declarative and reusable API views like components.

    This class provides a framework for defining API views with a declarative syntax
    and minimal boilerplate code. It handles setting up the HTTP methods, path, response
    status/body, among other configurations. It supports both synchronous and
    asynchronous handlers, allowing for flexible view implementations.

    This class is intended to be subclassed, not used directly.
    By subclassing, you can create custom API views that leverage the provided
    functionality, enabling you to refactor common view logic into reusable components.

    Args:
        path (str): The URL path to be used for this *path operation*. It can contain
            path parameters in the format `{parameter_name}`. For example, `"/{id}"`.

        methods (list[str] | set[str]): The HTTP methods that this view should handle.
            For example, `["GET"]` or `{"GET", "POST"}`. It can also receive StrEnum
            values, such as Python's [`http.HTTPMethod`](https://docs.python.org/3/library/http.html#http.HTTPMethod).

        auth (Any, optional): Authentication configuration for this *path operation*,
            which can be used to protect the endpoint. It can be a single authentication
            function or a list of authentication functions.
            [See more](https://django-ninja.dev/guides/authentication/).

        throttle (Any, optional): The application-level throttling configuration for
            this *path operation*, which can be used to limit the number of requests
            that can be made to the API in a given time frame. It can be a single
            throttling instance or a list of throttling instances.
            [See more](https://django-ninja.dev/guides/throttling/).

        response_schema (Any, optional): The type to use for the primary response.
            It can be any valid Pydantic field type, including Pydantic models,
            primitive types, or complex structures like `list` or `dict`.
            Defaults to `ninja.constants.NOT_SET`.

        status_code (int | None, optional): The default status code for the primary
            response. Can be an integer or an `IntEnum` (e.g., Python's
            [`http.HTTPStatus`](https://docs.python.org/3/library/http.html#http.HTTPStatus)).
            If not specified, defaults to `200` when a response_schema is provided.

        responses (dict[int, Any] | None, optional): Additional responses that could be
            returned by this *path operation*. The key is the status code, and the value
            is the response schema. These are merged with the primary response.
            Defaults to `None`.

        operation_id (str, optional): Custom operation ID to be used by this *path
            operation*. By default, it is generated automatically. If you provide a
            custom operation ID, you need to make sure it is unique for the whole API.
            [See more](https://django-ninja.dev/reference/operations-parameters/#operation_id).

        summary (str, optional): A summary for the *path operation*. If not provided,
            it's generated by capitalizing the operation function name, which is the
            `name` attribute here. It will be added to the generated OpenAPI.
            [See more](https://django-ninja.dev/reference/operations-parameters/#summary).

        description (str, optional): A description for the *path operation*. If not
            provided, it will be extracted automatically from the docstring of the
            *path operation function*. It can contain Markdown and will be added to the
            generated OpenAPI.
            [See more](https://django-ninja.dev/reference/operations-parameters/#description).

        tags (list[str], optional): A list of tags to be applied to the *path
            operation*. Read more about it in the
            [Django Ninja docs](https://django-ninja.dev/reference/operations-parameters/#tags).

        deprecated (bool, optional): Mark this *path operation* as deprecated. See more
            in the [Django Ninja docs](https://django-ninja.dev/reference/operations-parameters/#deprecated).

        response_schema_by_alias (bool, optional): Configuration passed to Pydantic to
            define if the response schema should be resolved by alias.
            Defaults to `False`.

        response_schema_exclude_unset (bool, optional): Configuration passed to Pydantic
            to define if the response data should have all the fields, including the
            ones that were not set and have their default values. This is different from
            `response_schema_exclude_defaults` in that if the fields are set, they will
            be included in the response, even if the value is the same as the default.
            When `True`, default values are omitted from the response.
            Defaults to `False`.

        response_schema_exclude_defaults (bool, optional): Configuration passed to
            Pydantic to define if the response data should have all the fields,
            including the ones that have the same value as the default. This is
            different from `response_model_exclude_unset` in that if the fields are set
            but contain the same default values, they will be excluded from the response.
            When `True`, fields with default values are omitted from the response.
            Defaults to `False`.

        response_schema_exclude_none (bool, optional): Configuration passed to Pydantic
            to define if the response data should exclude fields set to `None`. This is
            much simpler (less smart) than `response_model_exclude_unset` and
            `response_model_exclude_defaults`. You probably want to use one of those
            two instead of this one, as those allow returning `None` values when it
            makes sense. Defaults to `False`.

        url_name (str, optional): The name of the URL pattern that refers to this
            *path operation*. If not provided, it is generated from the operation
            function name, which is the `name` attribute here. Read more about it in
            the [Django Ninja docs](https://django-ninja.dev/reference/operations-parameters/#url_name)
            for more information. Defaults to `None`.

        include_in_schema (bool, optional): Whether to include this *path operation* in
            the generated OpenAPI schema. Read more about it in the
            [Django Ninja docs](https://django-ninja.dev/reference/operations-parameters/#include_in_schema)
            for more information. Defaults to `True`.

        openapi_extra (dict[str, Any], optional): Extra metadata to be included in the
            OpenAPI schema for this *path operation*. Read more about it in the
            [Django Ninja docs](https://django-ninja.dev/reference/operations-parameters/#openapi_extra)

        # Custom attributes
        name (str, optional): The name of the view function, used by the OpenAPI docs.
            If not provided, defaults to the class attribute name if the view is part
            of a viewset. Defaults to `None`.
        decorators (list[Callable], optional): View function decorators
            (applied in reverse order). Defaults to `None`.

    Examples:

    Thanks to the flexibility of `APIView`, you can create a wide variety of views
    with minimal boilerplate code. Here are examples of how you can create simple
    reusable read views supporting models with a UUID primary key, in both
    synchronous and asynchronous variants:

    Synchronous:
    ```python
    from typing import Any
    from uuid import UUID

    from django.http import HttpRequest
    from django.db import models
    from ninja.constants import NOT_SET
    from ninja_crud.views import APIView

    class ReadView(APIView):
        def __init__(
            self,
            response_schema: Any = NOT_SET,
            model: type[models.Model] | None = None,
            name: Optional[str] = None,
        ) -> None:
            super().__init__(
                path="/{id}",
                methods=["GET"],
                response_schema=response_schema,
                status_code=200,
                name=name,
            )
            self.model = model

        def endpoint(self, request: HttpRequest, id: UUID) -> models.Model:
            return self.model.objects.get(id=id)
    ```

    Asynchronous:
    ```python
    class AsyncReadView(APIView):
        def __init__(
            self,
            response_schema: Any = NOT_SET,
            model: type[models.Model] | None = None,
            name: Optional[str] = None,
        ) -> None:
            super().__init__(
                path="/async/{id}",
                methods=["GET"],
                response_schema=response_schema,
                status_code=200,
                name=name,
            )
            self.model = model

        async def endpoint(self, request: HttpRequest, id: UUID) -> models.Model:
            return await self.model.objects.aget(id=id)
    ```

    You can then use these views with a simple Django `models.Model`:
    ```python
    # examples/models.py
    import uuid
    from django.db import models

    class Department(models.Model):
        id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
        title = models.CharField(max_length=100, unique=True)
    ```

    And a `ninja.Schema` for serializing the response body:
    ```python
    # examples/schemas.py
    from uuid import UUID
    import ninja

    class DepartmentOut(ninja.Schema):
        id: UUID
        name: str
    ```

    Now, you can declaratively create endpoints using these view classes:
    ```python
    # examples/views.py
    from ninja import NinjaAPI

    from examples.models import Department
    from examples.schemas import DepartmentOut
    from examples.reusable_views import ReadView, AsyncReadView

    api = NinjaAPI()

    ReadView(
        name="read_department",
        model=Department,
        response_schema=DepartmentOut
    ).add_view_to(api)

    AsyncReadView(
        name="async_read_department",
        model=Department,
        response_schema=DepartmentOut
    ).add_view_to(api)
    ```

    Or, you can create a viewset to group related views:
    ```python
    # examples/views.py
    from ninja import NinjaAPI
    from ninja_crud.viewsets import APIViewSet

    from examples.models import Department
    from examples.schemas import DepartmentOut
    from examples.reusable_views import ReadView, AsyncReadView

    api = NinjaAPI()

    class DepartmentViewSet(APIViewSet):
        api = api
        model = Department

        read_department = ReadView(response_schema=DepartmentOut)
        async_read_department = AsyncReadView(response_schema=DepartmentOut)
    ```

    This setup provides both synchronous and asynchronous endpoints for reading
    department data, demonstrating the flexibility of the APIView class in handling
    different types of request handlers.
    """

    parent: Optional["APIViewSet"] = None  # TODO: keep here?

    def __init__(
        self,
        methods: list[str],
        path: str,
        *,
        # Response configuration
        response_schema: Any = NOT_SET,
        status_code: Optional[int] = None,
        responses: Optional[dict[int, Any]] = None,
        response_schema_by_alias: bool = False,
        response_schema_exclude_unset: bool = False,
        response_schema_exclude_defaults: bool = False,
        response_schema_exclude_none: bool = False,
        # Security and performance
        auth: Any = NOT_SET,
        throttle: Any = NOT_SET,
        decorators: Optional[list[Decorator]] = None,
        # OpenAPI documentation
        operation_name: Optional[
            str
        ] = None,  # Explain in a dedicated doc page why I named it like that
        operation_id: Optional[str] = None,
        summary: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[list[str]] = None,
        deprecated: Optional[bool] = None,
        include_in_schema: bool = True,
        openapi_extra: Optional[dict[str, Any]] = None,
        # URL configuration
        url_name: Optional[str] = None,
    ) -> None:
        self.path = path
        self.methods = methods
        self.response_schema = response_schema
        self.status_code = status_code
        self.responses = responses or {}
        self.auth = auth
        self.throttle = throttle
        self.decorators = decorators or []
        self.operation_name = operation_name
        self.operation_id = operation_id
        self.summary = summary
        self.description = description
        self.tags = tags
        self.deprecated = deprecated
        self.response_schema_by_alias = response_schema_by_alias
        self.response_schema_exclude_unset = response_schema_exclude_unset
        self.response_schema_exclude_defaults = response_schema_exclude_defaults
        self.response_schema_exclude_none = response_schema_exclude_none
        self.url_name = url_name
        self.include_in_schema = include_in_schema
        self.openapi_extra = openapi_extra

    @abc.abstractmethod
    def endpoint(self, *args: Any, **kwargs: Any) -> Any:
        """
        The endpoint function for the view. This method must be implemented in
        subclasses and should contain the view's business logic.

        This method can be implemented as either a synchronous or an asynchronous
        function, depending on the needs of the specific view. The APIView class
        will automatically adapt to the chosen implementation.

        For synchronous implementation:
        def endpoint(self, request: HttpRequest, ...) -> Any:
            # Synchronous logic here

        For asynchronous implementation:
        async def endpoint(self, request: HttpRequest, ...) -> Any:
            # Asynchronous logic here

        Args:
            *args (Any): Variable positional arguments.
            **kwargs (Any): Variable keyword arguments.

        Returns:
            Any: The response data. This can be a simple value, a model instance,
                 or any other data that can be serialized by Django Ninja.
        """

    def register(self, router: Union[NinjaAPI, Router]) -> None:
        """
        Register this view as an API endpoint with the given API or router.
        It handles the convertion of the view into an API operation and adds it to
        the API or router.

        Args:
            router (ninja.NinjaAPI | ninja.Router): The API or router to
                register the view with.

        Example:
        ```python
        from ninja import Router
        from examples.models import Department
        from examples.schemas import DepartmentOut
        from examples.reusable_views import ReadView

        router = Router()
        ReadView(Department, DepartmentOut).register(router)
        ```
        """
        router = router.default_router if isinstance(router, NinjaAPI) else router
        router.add_api_operation(
            path=self.path,
            methods=self.methods,
            view_func=self._build_view_func(),
            auth=self.auth,
            throttle=self.throttle,
            response=self._build_response(),
            operation_id=self.operation_id,
            summary=self.summary,
            description=self.description,
            tags=self.tags,
            deprecated=self.deprecated,
            by_alias=self.response_schema_by_alias,
            exclude_unset=self.response_schema_exclude_unset,
            exclude_defaults=self.response_schema_exclude_defaults,
            exclude_none=self.response_schema_exclude_none,
            url_name=self.url_name,
            include_in_schema=self.include_in_schema,
            openapi_extra=self.openapi_extra,
        )

    def _build_view_func(self) -> Callable:
        if self.operation_name is not None:
            self.endpoint.__name__ = self.operation_name

        return functools.reduce(
            lambda f, g: g(f),
            reversed(self.decorators),
            utils.to_function(self.endpoint),
        )

    def _build_response(self) -> Any:
        responses: dict[int, Any] = {}
        if self.response_schema is not NOT_SET:
            responses[self.status_code or 200] = self.response_schema
        elif self.status_code is not None:
            responses[self.status_code] = None

        responses.update(self.responses)
        return responses or NOT_SET
