name: docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to generate documentation for'
        required: true

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Generate documentation
      run: |
        uv run docs/scripts/convert_docstrings_to_markdown.py

    - name: Apply readme.io metadata to markdown files
      run: |
        uv run docs/scripts/apply_metadata_to_markdown.py

    - name: Publish documentation to readme.io
      uses: readmeio/rdme@v8
      with:
        rdme: docs ./docs --key=${{ secrets.README_TOKEN }} --version=${{ inputs.version }}
